@extends('theme2.layout.master')
@section('title', 'Muypil - ' . __('theme2-global.meta-title'))
@section('content')
    @include('theme2.sections.header-light')
    @include('theme2.sections.header-title')
    @include('theme2.sections.header-cards')
    @include('theme2.sections.partners')
    @include('theme2.sections.what-i-do')
    @include('theme2.sections.plans')
    @include('theme2.sections.faq')
    @include('theme2.sections.comments')
    @include('theme2.sections.company-facts')
    @include('theme2.sections.footer')
@endsection
