@extends('theme2.layout.master')
@section('title', 'Muypil - ' . __('theme2-global.comments'))
@section('content')
    @include('theme2.sections.header-light')
    @include('theme2.sections.comments-header')
    @include('theme2.sections.comments-comment')
    @include('theme2.sections.faq')
    @include('theme2.sections.company-facts')
    @include('theme2.sections.footer')
@endsection
